### PR TITLE
Upgrade Gradle version

### PR DESCRIPTION
**Pull request by w568w**
This PR upgrades the Gradle version used in the project from 7.6 to 8.11, because Gradle 7.6 is unsupported on Java 21 toolchain.

**Note**: it includes some hacks and dirty workarounds, only to ensure successful compilation. Please review all commits carefully before merging.

### CODE REVIEW

**Comment by w568w** [comment]
I am pinging everyone who could be interested (or affected) in this PR.

**Comment by w568w** [comment]
MiPush seems to be broken by this PR:

```
W/XMPush-7670( 7670): [Tid:8078] sdk_version = 5_7_8-C
V/XMPush-7670( 7670): [Tid:8078] loadClass fail hasContext= true, errMsg = com.android.id.impl.IdProviderImpl
V/XMPush-7670( 7670): [Tid:8078] miui load class error
V/XMPush-7670( 7670): java.lang.ClassNotFoundException: loadClass fail 
V/XMPush-7670( 7670): 	at com.xiaomi.push.r.a(SourceFile:170)
V/XMPush-7670( 7670): 	at com.xiaomi.push.au.a(SourceFile:46)
V/XMPush-7670( 7670): 	at com.xiaomi.push.au.<init>(SourceFile:41)
V/XMPush-7670( 7670): 	at com.xiaomi.push.av.a(SourceFile:29)
V/XMPush-7670( 7670): 	at com.xiaomi.push.aw.<init>(SourceFile:31)
V/XMPush-7670( 7670): 	at com.xiaomi.push.aw.a(SourceFile:40)
V/XMPush-7670( 7670): 	at com.xiaomi.mipush.sdk.MiPushClient.initialize(SourceFile:228)
V/XMPush-7670( 7670): 	at com.xiaomi.mipush.sdk.MiPushClient.access$100(SourceFile:63)
V/XMPush-7670( 7670): 	at com.xiaomi.mipush.sdk.MiPushClient$1.run(SourceFile:169)
V/XMPush-7670( 7670): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
V/XMPush-7670( 7670): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
V/XMPush-7670( 7670): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
V/XMPush-7670( 7670): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
V/XMPush-7670( 7670): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
V/XMPush-7670( 7670): 	at java.lang.Thread.run(Thread.java:1012)
V/XMPush-7670( 7670): Caused by: java.lang.ClassNotFoundException: com.android.id.impl.IdProviderImpl
V/XMPush-7670( 7670): 	at java.lang.Class.classForName(Native Method)
V/XMPush-7670( 7670): 	at java.lang.Class.forName(Class.java:607)
V/XMPush-7670( 7670): 	at java.lang.Class.forName(Class.java:512)
V/XMPush-7670( 7670): 	at com.xiaomi.push.r.a(SourceFile:167)
V/XMPush-7670( 7670): 	... 14 more
V/XMPush-7670( 7670): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.id.impl.IdProviderImpl" on path: DexPathList[[zip file "/data/app/~~X05Ogv9GJnUDHFsc2HZAKg==/io.github.danxi_dev.dan_xi-S2VLHBlyIGepzV_RVtOOug==/base.apk"],nativeLibraryDirectories=[/data/app/~~X05Ogv9GJnUDHFsc2HZAKg==/io.github.danxi_dev.dan_xi-S2VLHBlyIGepzV_RVtOOug==/lib/arm64, /data/app/~~X05Ogv9GJnUDHFsc2HZAKg==/io.github.danxi_dev.dan_xi-S2VLHBlyIGepzV_RVtOOug==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
V/XMPush-7670( 7670): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
V/XMPush-7670( 7670): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
V/XMPush-7670( 7670): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
V/XMPush-7670( 7670): 	... 18 more
```

**Review by ivanfei-1 — APPROVED** [review]
LGTM.

**Comment by w568w** [comment]
> com.android.id.impl.IdProviderImpl

Seems like a platform problem: <https://www.volcengine.com/docs/6285/66152>. Nothing to do with us. Maybe I will upgrade the dependency later.

**Pull request merged**
