### PR TITLE
Fix #226 and upgrade dependencies (Fixed)

### LINKED ISSUE #226: [BUG] 部分设备上无法选中标签
**复现步骤**
复现该 Bug 的步骤：
1. 到树洞编辑器页面
2. 点击 Tag，随便选择若干 Tag
3. 继续选择时，突然无法选中列表项。表现为点击屏幕任意处，列表都会关闭

**截图**
<video src="https://user-images.githubusercontent.com/8389787/227709886-9f5d0c25-5b33-49ed-b660-711831edb54f.mp4"/>

**系统信息**
 - 设备型号：n/a
 - 系统版本：Android
 - 旦夕版本（见「设置-关于本应用」）：1.3.11

### PR DESCRIPTION
**Pull request by w568w**
This PR fixes #226 and upgrade dependencies.

This PR is a subsequent version of #316, containing the changes:

- Downgrade `flutter_secure_storage` and `encrypt_shared_preferences` for now, before we found why it was broken;
- Update to Flutter 3.16.3.

I also applied `dart fix` to adapt to the recently introduced `super.xxx` syntax.

### CODE REVIEW

**Comment by ivanfei-1** [comment]
I will have a look as soon as the exams end.

**Comment by ivanfei-1** [comment]
But why upgrading these two packages is necessary? I don't quite get it.

**Comment by w568w** [comment]
> But why upgrading these two packages is necessary? I don't quite get it.

I suppose upgrading is necessary for any package. We have no special reason to stay at the old version.

**Comment by ivanfei-1** [comment]
Look good to me. This pr can be merged.

**Pull request merged**
