### PR TITLE
feat: add version for forum answer question api

### PR DESCRIPTION
**Pull request by JingYiJun**

### CODE REVIEW

**Review by HydrogenC — CHANGES_REQUESTED** [review]
I doubt if it's necessary to introduce a new dependency for returning multiple values. Using the builtin `record` language feature in Dart would be a better choice.  
Please refer to: https://dart.dev/language/records  
PS: This syntax is borrowed from C# actually

**Comment by w568w** [comment]
> I doubt if it's necessary to introduce a new dependency for returning multiple values. Using the builtin `record` language feature in Dart would be a better choice.

Also, we have https://github.com/DanXi-Dev/DanXi/blob/main/lib/model/pair.dart for pre-`record` era.

**Comment by HydrogenC** [comment]
> > I doubt if it's necessary to introduce a new dependency for returning multiple values. Using the builtin `record` language feature in Dart would be a better choice.
> 
> Also, we have https://github.com/DanXi-Dev/DanXi/blob/main/lib/model/pair.dart for pre-`record` era.

It isn't needed any more right now, is it?

**Review by HydrogenC — APPROVED** [review]

**Comment by w568w** [comment]
> It isn't needed any more right now, is it?

Yeah, of course.

**Comment by HydrogenC** [comment]
It looks good enough to me, so may we merge this right now @w568w ?

**Review by w568w — APPROVED** [review]
LGTM! Just let it go.

**Pull request merged**
