### PR TITLE
fix: timetable week problem

### LINKED ISSUE #217: [BUG] Wrong timetable display
**Bug description**
According to FDU's timetable, Sunday should be the first day of a school week. Setting it to Monday causes the courses on Sundays to be displayed a week later.

**Screenshot**
An example of the affected courses:
image_03B02211-B999-465F-93D8-E5E5CBAF1B51
image_04B1CDEE-405C-43DE-B384-51B1C3ED7D14

### PR DESCRIPTION
**Pull request by ivanfei-1**
Move the courses on Sundays a week forward to match the school schedule.
Close #217.

### CODE REVIEW

**Comment by w568w** [comment]
Could there be a chance that a `Course` is on both Sunday and Monday? 

Say, course A is on Week 1's Sun. & Mon. (i.e. 2/19 & 2/20) in this term. Under your `any()` assertion, it will be add to both Week 0 and 1 (i.e. 2/13, 2/19, 2/20 and 2/26). 

Consider moving assessments like `course.times!.any((element) => element.weekDay != 6))` into the inner `for` loop.

**Review by w568w — CHANGES_REQUESTED** [review]
As above.

**Comment by ivanfei-1** [comment]
Fixed.

**Review by ivanfei-1 — COMMENTED** [review]
Fixed.

**Review by w568w — APPROVED** [review]

**Pull request merged**
