### PR TITLE
feat: show DanXi Care dialog when attempting to send posts with care words

### PR DESCRIPTION
**Pull request by kooWZ**
Issue #235 
The first time a user attempts to send posts with care words, DanXi Care dialog box will pop up, and the message will not be sent.
Only when clicking again will the post be actually sent.

PS. What's the necessity to use `WidgetsBinding.instance.addPostFrameCallback` here and in commit 52f547f ?

[[lib/page/opentreehole/hole_search.dart](https://github.com/DanXi-Dev/DanXi/blob/52f547fe74e7aab2e2825e600c7a7c042f705186/lib/page/opentreehole/hole_search.dart#L176)](https://github.com/DanXi-Dev/DanXi/blob/52f547fe74e7aab2e2825e600c7a7c042f705186/lib/page/opentreehole/hole_search.dart#L176-L183)

### CODE REVIEW

**Comment by w568w** [comment]
Look almost good to me.

> What's the necessity to use `WidgetsBinding.instance.addPostFrameCallback` here and in commit https://github.com/DanXi-Dev/DanXi/commit/52f547fe74e7aab2e2825e600c7a7c042f705186 ?

No idea and I do not suppose it is essential. Maybe ask @Boreas618.

**Comment by Boreas618** [comment]
> What's the necessity to use WidgetsBinding.instance.addPostFrameCallback here and in commit https://github.com/DanXi-Dev/DanXi/commit/52f547fe74e7aab2e2825e600c7a7c042f705186 ?

To address the warning about the **asynchronous build context**. This is not a recommended practice as it can be confusing to understand. Perhaps I can refactor this section using the instructions provided [here](https://dart.dev/tools/linter-rules/use_build_context_synchronously).

**Comment by Boreas618** [comment]
In my opinion, we can implement the detection of care words using the `PostInterceptor`. This would result in more consistent source code. Please refer to the implementation of `_kStopWordInterceptor` for an example.

**Comment by w568w** [comment]
> > What's the necessity to use WidgetsBinding.instance.addPostFrameCallback here and in commit [52f547f](https://github.com/DanXi-Dev/DanXi/commit/52f547fe74e7aab2e2825e600c7a7c042f705186) ?
> 
> To address the warning about the **asynchronous build context**. This is not a recommended practice as it can be confusing to understand. Perhaps I can refactor this section using the instructions provided [here](https://dart.dev/tools/linter-rules/use_build_context_synchronously).

Nope... I do not think it will address the warning. It just *bypasses* the warning in a way that the linter is not smart enough to recognize, and indeed makes the thing worse: 

Linter will complain when using a `context` after an asynchronous gap, because we cannot know whether the `context` is still effective after the gap. Look at the code below:

```dart
// We are in a normal button's onTap() callback.
final text = _controller.text;
await aVeryLongOperation(text); // this operation takes very long, up to 1 hour!
Noticing.showNotice(context, "Hey, We Are Done"); // use the context across the "asynchronous gap" above
```

Say that a user clicks the button, and before `aVeryLongOperation()` gets done, he exits the page containing this button, so the button gets "destroyed". 

Now what about the running `onTap`? Will it be canceled? No. Actually it executes until the last line. When `await aVeryLongOperation` finally finishes, `context` is used in calling `Noticing.showNotice` then. However, since the button has been destroyed a long time ago, of course the `context` is invalid now (or specifically, `context.mounted == false`), and `Noticing.showNotice` will eventually get crashed. That's why we should check whether `context.mounted` after awaiting an asynchronous function (i.e. "asynchronous gap").

So if you put `Noticing.showNotice(context, "Hey, We Are Done")` in a `addPostFrameCallback`, you are at one step further to postponing the usage of `context`, making it more likely to have become unusable when reaching for it; thus, let the thing be worse.

**Comment by Boreas618** [comment]
Got it

> > > What's the necessity to use WidgetsBinding.instance.addPostFrameCallback here and in commit [52f547f](https://github.com/DanXi-Dev/DanXi/commit/52f547fe74e7aab2e2825e600c7a7c042f705186) ?
> > 
> > 
> > To address the warning about the **asynchronous build context**. This is not a recommended practice as it can be confusing to understand. Perhaps I can refactor this section using the instructions provided [here](https://dart.dev/tools/linter-rules/use_build_context_synchronously).
> 
> Nope... I do not think it will address the warning. It just _bypasses_ the warning in a way that the linter is not smart enough to recognize, and indeed makes the thing worse:
> 
> The reason why linter will complain when using a `context` after an asynchronous gap is that, we cannot know whether the `context` is still effective after the gap. Look at the code below:
> 
> ```dart
> // We are in a normal button's onTap() callback.
> final text = _controller.text;
> await aVeryLongOperation(text); // this operation takes very long, up to 1 hour!
> Noticing.showNotice(context, "Hey, We Are Done"); // use the context across the "asynchronous gap" above
> ```
> 
> Say that a user clicks the button, and before `aVeryLongOperation()` gets done, he exits the page containing this button, so the button gets "destroyed".
> 
> Now what about the running `onTap`? Will it be canceled? No. Actually it executes until the last line. When `await aVeryLongOperation` finally finishes, `context` is used in calling `Noticing.showNotice` then. However, since the button has been destroyed a long time ago, of course the `context` is invalid now (or specifically, `context.mounted == false`), and `Noticing.showNotice` will eventually get crashed. That's why we should check whether `context.mounted` after awaiting an asynchronous function (i.e. "asynchronous gap").
> 
> So if you put `Noticing.showNotice(context, "Hey, We Are Done")` in a `addPostFrameCallback`, you are at one step further to postponing the usage of `context`, making it more likely to have become unusable when reaching for it; thus, let the thing be worse.

**Comment by kooWZ** [comment]
> In my opinion, we can implement the detection of care words using the `PostInterceptor`. This would result in more consistent source code. Please refer to the implementation of `_kStopWordInterceptor` for an example.

I think it would be complicated to achieve the effect of sending posts only on the second click using `PostInterceptor`.

**Comment by Boreas618** [comment]
LGTM

**Pull request merged**
